apiVersion: v1
kind: Pod
metadata:
  name: cs-nginx-pod
  labels:
    cs-label: proxy
spec:
  containers:
  - name: cs-nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: cs-nginx-port

---
apiVersion: v1
kind: Service
metadata:
  name: cs-nginx-service
spec:
  selector:
    cs-label: proxy
  ports:
  - name: cs-service-port
    protocol: TCP
    port: 80
    targetPort: cs-nginx-port



---
kind: Service 
apiVersion: v1 
metadata:
  name: cs-nodeport-service 
spec:
  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster 
  type: NodePort

  # When the node receives a request on the static port (30163)
  # "select pods with the label 'app' set to 'echo-hostname'"
  # and forward the request to one of them
  selector:
    cs-label: proxy

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - nodePort: 30163
      port: 8081
      targetPort: cs-nginx-port