apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: cs-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cs-nginx
  template:
    metadata:
      labels:
        app: cs-nginx
    spec:
      containers:
      - name: cs-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
